apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "adv-layout-repl"
spec:
  configuration:
    clusters:
      - name: adv
        layout:
          shardsCount: 4
          replicas:
            - templates:
                podTemplate: clickhouse:22.1
              httpPort: 8000
              tcpPort: 8001
              interserverHTTPPort: 8002
            - templates:
                podTemplate: clickhouse:22.2
              httpPort: 9000
              tcpPort: 9001
              interserverHTTPPort: 9002
            - templates:
                podTemplate: clickhouse:22.3
              httpPort: 10000
              tcpPort: 10001
              interserverHTTPPort: 10002

  templates:
    podTemplates:

      - name: clickhouse:22.1
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.1

      - name: clickhouse:22.3
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.2


      - name: clickhouse:22.3
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.3
