apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "version-update"
spec:
  configuration:
    clusters:
      - name: update
        templates:
          podTemplate: clickhouse:22.2
        layout:
          shards:
            - replicas:
                - tcpPort: 9000
                - tcpPort: 9000
                - tcpPort: 9000
                  templates:
                    podTemplate: clickhouse:22.3

  templates:
    podTemplates:
      - name: clickhouse:22.2
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.2

      - name: clickhouse:22.3
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.3
